# Generated by Django 2.1b1 on 2018-07-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronaldo', '0002_links_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link_logo',
            field=models.CharField(max_length=1000),
        ),
    ]
