# Generated by Django 2.1b1 on 2018-07-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronaldo', '0003_auto_20180724_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='the_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
