# Generated by Django 2.1b1 on 2018-08-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ronaldo', '0005_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ronaldo.Match'),
        ),
    ]
