# Generated by Django 2.1b1 on 2018-08-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronaldo', '0006_auto_20180802_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='title',
            new_name='match',
        ),
    ]
