# Generated by Django 2.1b1 on 2018-08-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronaldo', '0007_auto_20180802_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link_logo',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
